[project]
name = "amii-tp1"
version = "0.1.0"
description = "Trabajo Práctico 1 de Análisis Matemático II"
authors = [
  {name = "Martín Stanicio", email = "mstanicio@frd.utn.edu.ar"},
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "matplotlib>=3.10.5",
  "numpy>=2.3.2",
]
